### ISSUE TITLE
Lista de Contatos Não Atualiza

### ISSUE THREAD

**Issue by flaviossantana** [alura-cursos/flutter-persistencia-interna#1]
Após inserir um novo contato, ao voltar para a lista de contatos o item recém inserido não está sendo apresentado.

**Comment by jsantos93** [comment]
Eu vi que se atualizar para StatefulWidget ele funciona, mas aqui não pegou.

**Comment by moisesfilho** [comment]
Minha implementação também ficou com o mesmo comportamento. Não consegui pegar o que pode estar diferente... nem nos vídeos.

**Comment by alexfelipe** [comment]
Oi gente, eu deixei uma atividade no curso indicando que o motivo de não atualizar está relacionado ao Widget ser `StatelessWidget`, portanto, apenas modifique para `StatefulWidget`.

**Comment by Potteer** [comment]
Alex, realizei tal modificação no StatelessWidget e mesmo assim não atualiza sozinho. Preciso voltar a home e após clicar em contacts, ai sim atualiza pegando o novo contact. Preciso add o setState nesse caso para funcionar?

**Comment by alexfelipe** [comment]
Em casos que a atualização não é feita automática, provavelmente é necessário o uso do `setState()`.
